global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus_metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dummy_vm'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'dummy_app'
    scheme: 'https'
    static_configs:
      - targets: ['metrics.servercare.id']